### ISSUE TITLE
Icons not fading all the away on Classic

### ISSUE THREAD

**Issue by Zerodeck** [aduth/Doom_CooldownPulse#9]
Hello, using this on classic the CD icon does not fade all the way frequently with Frost Nova and Flame Blast.

![image](https://github.com/aduth/Doom_CooldownPulse/assets/24996534/890b4ce0-4d83-416a-8147-c756d7f63ab6)

**Comment by aduth** [comment]
Hey, thanks for flagging this issue. I've seen some comments about issues with HC Classic, but I don't currently have an active WoW subscription to be able to test a new version.

Others have reported having some success using the version intended for WoTLK Classic. Could you give that a try and see if it works any better for you?

**Comment by Zerodeck** [comment]
Hey will do! It's like it stops fading at the last second on the classic
version

**Comment by Zerodeck** [comment]
Hey I tried the WOTLK version but it seems it won't even work through curseforge.

![image](https://github.com/aduth/Doom_CooldownPulse/assets/24996534/f0709edd-0473-4dc8-83e8-32fc1f88aa21)

**Comment by aduth** [comment]
You'll have to download and install it manually, instead of through the CurseForge app.

1. Download from CurseForge: https://www.curseforge.com/wow/addons/doomcooldownpulse/download/4489489
2. Unzip and find the folder `Doom_CooldownPulse` that has files in it. It might be inside the folder where you extract it to.
3. Move the `Doom_CooldownPulse` folder with the files into `C:\Program Files (x86)\World of Warcraft\_classic_era_\Interface\AddOns`
4. Restart the game

The game will probably tell you that the addon is out-of-date, but it should work.

**Comment by Zerodeck** [comment]
Hey, yeah the WOTLK version works sorry for the late reply!

**Comment by aduth** [comment]
Glad to hear it’s working! I’ll keep the issue open, since I still want to solve it for the Classic version, but good to know the workaround is an option in the meantime.

**Comment by aduth** [comment]
I’ve since resubscribed ahead of Season of Discovery and was able to get a new version for Classic tested and published to CurseForge, so you shouldn’t have to manually use the WoTLK version anymore.

I’m hoping this will work for Season of Discovery, but since there’s no PTR for it, I’ll have to wait and see if anything breaks once that goes live. I’ll try to get an updated version out ASAP if that happens.
